### ISSUE TITLE
User Stories: Main Page View

### ISSUE THREAD

**Issue by bhohnco** [Walk-Safe/walk-safe-frontend#8]
1. User opens the application 
2. User sees their name displayed on the page
3. User sees the options for starting point, and an endpoint for the trip.
4. User selects a start point and endpoint. 
5. User sees transportation options dropdown menu. 
6. User selects a transportation option.
7. User sees a contacts drop-down menu.
8. User selects a contact/phone number
9. User select "Submit Trip" button
10. Modal appears with Trip ETA

**Comment by carolineshowscode** [comment]
Completed
